name: Publish Package
on:
  release:
    types: [published]
jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v2.3.3
      - name: Set-up Latest Node.js LTS
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"
          check-latest: true
          registry-url: https://registry.npmjs.org/
      - name: Install NPM Dependency Packages
        run: npm install --legacy-peer-deps
      - name: Publish NPM Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}